import { jsPDF } from 'jspdf';
import { sanitizeReportText } from '@/lib/utils';

export interface ResultData {
  name: string;
  email: string;
  department: string;
  resumeScore: number;
  technicalScore: number;
  psychometricScore: number;
  finalScore: number;
  recommended: boolean;
}

export function generateResultPDF(data: ResultData) {
  const doc = new jsPDF();
  const navy = [30, 58, 95];
  const gold = [212, 168, 67];

  const candidateName = sanitizeReportText(data.name);
  const candidateEmail = sanitizeReportText(data.email);
  const candidateDepartment = sanitizeReportText(data.department);
  const recommendationLabel = data.recommended ? 'Recommended Faculty' : 'Not Recommended Faculty';

  // Header
  doc.setFillColor(navy[0], navy[1], navy[2]);
  doc.rect(0, 0, 210, 45, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('Faculty Recruitment Result', 105, 20, { align: 'center' });
  doc.setFontSize(11);
  doc.text('AI-Powered Evaluation Report', 105, 30, { align: 'center' });
  doc.setFillColor(gold[0], gold[1], gold[2]);
  doc.rect(0, 45, 210, 3, 'F');

  // Candidate info
  doc.setTextColor(30, 58, 95);
  doc.setFontSize(14);
  doc.text('Candidate Information', 20, 62);
  doc.setDrawColor(212, 168, 67);
  doc.line(20, 65, 190, 65);

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const info = [
    ['Name:', candidateName],
    ['Email:', candidateEmail],
    ['Department:', candidateDepartment],
  ];
  info.forEach(([label, value], i) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 25, 75 + i * 10);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 70, 75 + i * 10);
  });

  // Scores
  doc.setTextColor(30, 58, 95);
  doc.setFontSize(14);
  doc.text('Evaluation Scores', 20, 115);
  doc.setDrawColor(212, 168, 67);
  doc.line(20, 118, 190, 118);

  const scores = [
    ['Resume Analysis Score (30%)', `${data.resumeScore}/100`],
    ['Technical Assessment Score (50%)', `${data.technicalScore}/100`],
    ['Psychometric Evaluation Score (20%)', `${data.psychometricScore}/100`],
  ];

  doc.setFontSize(11);
  scores.forEach(([label, value], i) => {
    doc.setTextColor(60, 60, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(label, 25, 130 + i * 12);
    doc.setFont('helvetica', 'bold');
    doc.text(value, 170, 130 + i * 12, { align: 'right' });
  });

  // Final Score box
  doc.setFillColor(navy[0], navy[1], navy[2]);
  doc.roundedRect(20, 168, 170, 25, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Final Score', 30, 183);
  doc.setFontSize(20);
  doc.text(`${data.finalScore.toFixed(1)}/100`, 170, 184, { align: 'right' });

  // Recommendation
  const recY = 210;
  if (data.recommended) {
    doc.setFillColor(34, 139, 34);
    doc.roundedRect(20, recY, 170, 20, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text(recommendationLabel, 105, recY + 13, { align: 'center' });
  } else {
    doc.setFillColor(200, 50, 50);
    doc.roundedRect(20, recY, 170, 20, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text(recommendationLabel, 105, recY + 13, { align: 'center' });
  }

  // Footer
  doc.setFillColor(navy[0], navy[1], navy[2]);
  doc.rect(0, 275, 210, 22, 'F');
  doc.setTextColor(180, 180, 180);
  doc.setFontSize(8);
  doc.text('This report was generated by the AI Faculty Recruitment System', 105, 283, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, 289, { align: 'center' });

  doc.save(`${candidateName.replace(/\s+/g, '_')}_Recruitment_Result.pdf`);
}
